{
 "title": "Resultados Testes",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "equipamentos",
    "label": "Equipamento",
    "query": "SELECT ID_EQUIP __value, mac __text FROM equipamento ORDER BY ID_EQUIP DESC;"
   }
  ]
 },
 "panels": [
  {
   "title": "Teste Destino 192.168.18.1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(data_hora_ping) as time_sec,\n  ms1 AS '192.168.18.1',\n  data_hora_ping as metric\nFROM ping\nWHERE $__timeFilter(data_hora_ping) AND equipamento = $equipamentos\nORDER BY data_hora_ping ASC\n"
    }
   ]
  },
  {
   "title": "Teste Destino 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(data_hora_ping) as time_sec,\n  ms2,\n  data_hora_ping as metric\nFROM ping\nWHERE $__timeFilter(data_hora_ping) AND equipamento = $equipamentos\nORDER BY data_hora_ping ASC\n"
    }
   ]
  },
  {
   "title": "Teste Destino 3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(data_hora_ping) as time_sec,\n  ms3,\n  data_hora_ping as metric\nFROM ping\nWHERE $__timeFilter(data_hora_ping) AND equipamento = $equipamentos\nORDER BY data_hora_ping ASC\n"
    }
   ]
  },
  {
   "title": "Teste de Velocidade",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(data_hora_speedtest) as time_sec,\n  download_speed, upload_speed,\n  data_hora_speedtest as metric\nFROM speedtest\nWHERE $__timeFilter(data_hora_speedtest) AND equipamento = $equipamentos\nORDER BY data_hora_speedtest ASC\n"
    }
   ]
  }
 ]
}